name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          
          days-before-issue-stale: 365
          days-before-issue-close: 30
          days-before-pr-stale: 365
          days-before-pr-close: 30

          exempt-issue-labels: 'pinned,security'
          exempt-pr-labels: 'pinned,security'
